### ISSUE TITLE
Compilation fails with >=openssl-3.0.0

### ISSUE THREAD

**Issue by ConiKost** [zhaozg/lua-openssl#239]
- `uname -a` or OS info: Linux Galactica 5.13.0-gentoo #1 SMP Sun Jul 4 22:14:43 CEST 2021 x86_64 Intel(R) Atom(TM) CPU C2758 @ 2.40GHz GenuineIntel GNU/Linux

- `openssl version` or OPENSSL_VERSION_TEXT in your opensslv.h: OpenSSL 3.0.0
- `lua -v` or `luajit -v`: Lua 5.4.2  Copyright (C) 1994-2020 Lua.org, PUC-Rio
- `lua -e "print(require'openssl'.version())" or `luajit -e "print(require'openssl'.version())"`: 0.8.0-6

**Problem details**
src/hmac.c:91:13: error: too few arguments to function ‘EVP_MAC_init’
Full build log: https://805962.bugs.gentoo.org/attachment.cgi?id=729261

**Steps/codes to reproduce the bug**

1. install openssl-3.0.0
2. compile with openssl-3.0.0

**Expected result**
Compiles with openssl-3.0.0.

**Additional context**
N/A

**Comment by zhaozg** [comment]
After openssl3 release, I'll do more about openssl3.

**Comment by ConiKost** [comment]
Thank you!
