### ISSUE TITLE
Not builds with MinGW 4.7.2

### ISSUE THREAD

**Issue by DangerPie** [zhaozg/lua-openssl#9]
Not builds with MinGW 4.7.2, but builds with 4.6.1; openssl-1.0.1c builds with 4.7.2

```
>make

gcc -g -fPIC -Wall -fPIC -I../lua-5.1.5/src -I"../openssl-1.0.1c/include"  -L../openssl-1.0.1c -L../lua-5.1.5/src -L./ -I../lua-5.1.5/src -I"../openssl-1.0.1c/include"  -L../openssl-1.0.1c -L../lua-5.1.5/src -L./ -c -o src/auxiliar.o src/auxiliar.c
src/auxiliar.c:1:0: warning: -fPIC ignored for target (all code is position independent) [enabled by default]
gcc -g -fPIC -Wall -fPIC -I../lua-5.1.5/src -I"../openssl-1.0.1c/include"  -L../openssl-1.0.1c -L../lua-5.1.5/src -L./ -I../lua-5.1.5/src -I"../openssl-1.0.1c/include"  -L../openssl-1.0.1c -L../lua-5.1.5/src -L./ -c -o src/bio.o src/bio.c
src/bio.c:1:0: warning: -fPIC ignored for target (all code is position independent) [enabled by default]
In file included from src/openssl.h:46:0,
                 from src/bio.c:23:
../openssl-1.0.1c/include/openssl/ssl.h:1284:2: error: expected specifier-qualifier-list before '(' token
In file included from src/bio.c:23:0:
src/openssl.h:93:0: warning: "strcasecmp" redefined [enabled by default]
In file included from d:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-mingw32/include/guiddef.h:139:0,
                 from d:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-mingw32/include/winnt.h:461,
                 from d:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-mingw32/include/windef.h:139,
                 from d:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-mingw32/include/windows.h:69,
                 from ../openssl-1.0.1c/include/openssl/rand.h:67,
                 from src/openssl.h:44,
                 from src/bio.c:23:
d:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-mingw32/include/string.h:106:0: note: this is the location of the previous definition
In file included from src/bio.c:23:0:
src/openssl.h:308:59: error: expected declaration specifiers or '...' before '(' token
makefile:11: recipe for target `src/bio.o' failed
make: *** [src/bio.o] Error 1
```
